### PR TITLE
Don't use stdin unless `--stdin` flag is specified

### LINKED ISSUE #11: Using in non-tty environment giving errors
I am using this cli tool in [lerna](https://github.com/lerna/lerna), which is not using tty channel to spawn child process for running npm scripts. In that case, the `chalk` command always faile with error code 1

```
Invalid style: THE_STRING_I_WANT_TO_LOG
```

Further investigate indicates if not using tty, this package is using `getStdin` from `get-stdin` to get the input, and trying to process all input as style. This is wrong as the data I want to print is also part of `styles` array, which is not a preset style, hence the error.

Run this in any non-tty process and you can reproduce the issue.

### PR DESCRIPTION
**Pull request by msabramo**
Before:
-------

```
$ echo '' | FORCE_COLOR=1 node cli.js green 'this is a test'
Invalid style: this is a test
```

After:
-------

```
$ echo '' | FORCE_COLOR=1 node cli.js green 'this is a test'
this is a test

$ echo '' | FORCE_COLOR=1 node cli.js green 'this is a test' | cat
this is a test

$ echo 'text from stdin' | node cli.js --stdin green
text from stdin
```

Fixes #11

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -39,18 +39,23 @@ const printAllStyles = () => {
 const cli = meow(`
 	Usage
 	  $ chalk <style> … <string>
-	  $ echo <string> | chalk <style> …
+	  $ echo <string> | chalk --stdin <style> …
 
 	Options
 	  --template, -t  Style template. The \`~\` character negates the style.
 	  --demo          Demo of all Chalk styles.
+	  --stdin         Read input from stdin rather than from arguments.
```
Comment (sindresorhus) [inline cli.js:46]: Put it below template.

File: cli.js [hunk 2]
```diff
@@ -39,18 +39,23 @@ const printAllStyles = () => {
...
 
 	Examples
 	  $ chalk red bold 'Unicorns & Rainbows'
 	  $ chalk -t '{red.bold Unicorns & Rainbows}'
 	  $ chalk -t '{red.bold Dungeons and Dragons {~bold.blue (with added fairies)}}'
+	  $ echo 'Unicorns from stdin' | chalk --stdin red bold
 `, {
 	flags: {
+		stdin: {
```
Comment (sindresorhus) [inline cli.js]: Put it below `template`

File: cli.js [hunk 3]
```diff
@@ -75,7 +80,7 @@ function init(data) {
 	console.log(fn(data.replace(/\n$/, '')));
 }
 
-if (process.stdin.isTTY || cli.flags.stdin === false) {
+if (process.stdin.isTTY || cli.flags.stdin !== true) {
```
Comment (sindresorhus) [inline cli.js]:
```suggestion
if (process.stdin.isTTY || !cli.flags.stdin) {
```

**Review by sindresorhus — CHANGES_REQUESTED** [review]

**Comment by sindresorhus** [comment]
You also need to update the readme.

**Comment by msabramo** [comment]
Thanks, @sindresorhus! I made the updates you requested in 915e1a6. If you want other changes or want me to squash, let me know.

**Review by Qix- — APPROVED** [review]
